apiVersion: v2
# When releasing, 'appVersion' is set by the Chart publishing process
appVersion: '2.26.6-branch.feat-fastspring.365-9980e39'
description: Speckle Server
home: 'https://speckle.systems/'
icon: 'https://app.speckle.systems/images/logo.png'
maintainers:
  - name: Speckle Systems
    url: 'https://speckle.systems/'
name: speckle-server
sources:
  - 'https://github.com/specklesystems/speckle-server'
type: application
# When releasing, 'version' is set by the Chart publishing process
version: 2.26.6-branch.feat-fastspring.365-9980e39
